{
 "title": "Schreibtisch",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Availaible Disk Space",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Watt",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "topic::tag" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "apower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "topic::tag" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "topic::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT mean(\"current\") FROM \"mqtt_consumer\" WHERE $timeFilter GROUP BY time($__interval), \"topic\"::tag fill(null)",
     "select": [
      [
       { "params": [ "current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "°C",
     "query": "SELECT mean(\"temperature_tC\") FROM \"mqtt_consumer\" WHERE $timeFilter GROUP BY time($__interval), \"topic\"::tag fill(linear)"
    }
   ]
  },
  {
   "title": "Gesamtverbrauch in kWh",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT sum(\"apower\") * (COUNT(\"apower\") / 3600) AS \"Leistungsaufnahme in kWh\"   FROM \"mqtt_consumer\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "apower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "query": "SELECT (sum(\"apower\") * (COUNT(\"apower\") / 3600) ) * 0.3577 AS \"Kosten in €\"   FROM \"mqtt_consumer\" WHERE $timeFilter GROUP BY time($__interval) fill(linear) "
    },
    {
     "query": "SELECT integral(\"apower\", 1h)  AS \"Leistungsaufnahme in kWh\"\nFROM \"mqtt_consumer\"\nWHERE $timeFilter\nGROUP BY time($__interval)\n\n"
    }
   ]
  }
 ]
}