---
- hosts: raspberrypi
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Mosquitto repository
      apt_repository:
        repo: ppa:mosquitto-dev/mosquitto-ppa
        state: present

    - name: Install Mosquitto
      apt:
        name: mosquitto
        state: present

    - name: Configure Mosquitto
      copy:
        dest: /etc/mosquitto/mosquitto.conf
        content: |
          pid_file /run/mosquitto/mosquitto.pid
          
          persistence true
          persistence_location /var/lib/mosquitto/
          
          log_dest file /home/siddy/mqtt/logfile.log
          log_type all
          log_timestamp true
          log_timestamp_format %Y-%m-%dT%H:%M:%S
          
          include_dir /etc/mosquitto/conf.d
          
          password_file /etc/mosquitto/pw.passwd
          allow_anonymous false
          
          listener 1883
          
          max_connections -1

    - name: Create log directory for Mosquitto
      file:
        path: /home/siddy/mqtt/logfile.log
        state: touch
        owner: mosquitto
        group: mosquitto
        mode: '0644'

    - name: Ensure /etc/mosquitto/conf.d directory exists
      file:
        path: /etc/mosquitto/conf.d
        state: directory
        owner: mosquitto
        group: mosquitto
        mode: '0755'

    - name: Restart Mosquitto service
      systemd:
        name: mosquitto
        state: restarted
        enabled: yes

    - name: Add InfluxData repository
      apt_key:
        url: https://repos.influxdata.com/influxdb.key
        state: present

    - name: Add InfluxData repository (continued)
      apt_repository:
        repo: deb https://repos.influxdata.com/debian buster stable
        state: present

    - name: Install InfluxDB, Telegraf, and Chronograf
      apt:
        name:
          - influxdb
          - telegraf
          - chronograf
        state: present

    - name: Start and enable InfluxDB service
      systemd:
        name: influxdb
        enabled: yes
        state: started

    - name: Start and enable Telegraf service
      systemd:
        name: telegraf
        enabled: yes
        state: started

    - name: Install Grafana repository
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Add Grafana repository
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present

    - name: Install Grafana
      apt:
        name: grafana
        state: present

    - name: Configure Grafana
      copy:
        dest: /etc/grafana/grafana.ini
        content: |
          #################################### Paths ####################################
          [paths]
          data = /var/lib/grafana
          logs = /var/log/grafana
          plugins = /var/lib/grafana/plugins

          #################################### Server ####################################
          [server]
          protocol = http
          http_port = 3000
          domain = localhost
          enforce_domain = false
          root_url = %(protocol)s://%(domain)s:%(http_port)s/

          #################################### Database ####################################
          [database]
          type = sqlite3
          path = grafana.db

          #################################### Auth ######################
          [auth.anonymous]
          enabled = false
          org_name = My castle
          org_role = Viewer

    - name: Start and enable Grafana service
      systemd:
        name: grafana-server
        enabled: yes
        state: started

    - name: Configure Telegraf for Mosquitto and InfluxDB
      copy:
        dest: /etc/telegraf/telegraf.conf
        content: |
          [global_tags]
          
          [agent]
            interval = "10s"
            round_interval = true
            metric_batch_size = 1000
            metric_buffer_limit = 10000
            collection_jitter = "0s"
            flush_interval = "10s"
            flush_jitter = "0s"
            precision = "0s"
            hostname = ""
            omit_hostname = false
            
          [[inputs.cpu]]
            percpu = true
            totalcpu = true
            collect_cpu_time = false
            report_active = false
            core_tags = false
            
          [[inputs.disk]]
            ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]
            
          [[inputs.diskio]]
          
          [[inputs.kernel]]
          
          [[inputs.mem]]
          
          [[inputs.processes]]
          
          [[inputs.swap]]
          
          [[inputs.system]]
          
          [[inputs.mqtt_consumer]]
            servers = ["tcp://raspberrypi:1883"]
            topics = [
              "shelly_lamp_1/#",
              "shelly_lamp_2/#",
              "shelly_dave_desk/#"
            ]
            username = "shelly"
            password = "pw123456"
            data_format = "json"
          
          [[outputs.influxdb]]
            urls = ["http://raspberrypi:8086"]
            database = "shelly"

    - name: Restart Telegraf service
      systemd:
        name: telegraf
        state: restarted

    - name: Create InfluxDB database
      influxdb_database:
        name: shelly
        state: present
